export const dynamic = "force-dynamic"; // catalogue is editable in admin, so never serve a stale build-time copy
import Link from "next/link";
import { config, ngn } from "@/config";
import { FAQ, STEPS } from "@/data/content";
import { listGamesWithFrom } from "@/lib/gamesWithPrices";
import { productService } from "@/services/productService";
import { GameCard } from "@/components/GameCard";
import { HeroVisual } from "@/components/HeroVisual";
import { TrustBadge } from "@/components/TrustBadge";
const WHY = [["Fast delivery", "Your top-up starts automatically as soon as payment is confirmed."], ["Secure payments", "Payments are handled by our payment provider. Your card details never touch our servers."], ["Naira pricing", "Clear prices in ₦ with no currency conversion surprises."], ["Transparent tracking", "Follow every order step by step, with or without an account."]];
export default async function Home() {
  const games = await listGamesWithFrom(), popular = (await Promise.all(games.map(async ({ game }) => (await productService.getProducts(game.id)).filter((p) => p.popular).map((p) => ({ ...p, game }))))).flat().slice(0, 4);
  const h2 = "mb-5 text-2xl font-semibold tracking-tight md:text-3xl";
  return (<div className="space-y-16">
    <section className="grid items-center gap-8 pt-4 md:grid-cols-[1.1fr_.9fr] md:pt-10"><div><h1 className="text-4xl font-semibold leading-[1.05] tracking-tight md:text-6xl">Top Up Your Game. <span className="bg-gradient-to-r from-hi to-brand2 bg-clip-text text-transparent">Instantly.</span></h1><p className="mt-4 max-w-lg text-lg text-ink2">Buy game credits and digital gaming products in Naira. Fast checkout, secure payments, and automatic delivery.</p>
      <div className="mt-6 flex flex-wrap gap-3"><Link href="/games" className="rounded-xl bg-gradient-to-br from-brand to-brand2 px-6 py-3.5 font-medium">Browse Games</Link><Link href="/how-it-works" className="rounded-xl border border-line px-6 py-3.5 text-ink2 hover:border-hi">How It Works</Link></div>
      <div className="mt-7 flex flex-wrap gap-x-6 gap-y-2"><TrustBadge>Instant Delivery</TrustBadge><TrustBadge>Secure Payments</TrustBadge><TrustBadge>Naira Pricing</TrustBadge><TrustBadge>24/7 Support</TrustBadge></div></div><div className="hidden md:block"><HeroVisual /></div></section>
    <section><h2 className={h2}>Popular Games</h2>{games.length ? <div className="grid grid-cols-2 gap-4 md:grid-cols-4">{games.map(({ game, from }) => <GameCard key={game.id} game={game} from={from} />)}</div> : <p className="rounded-2xl border border-line bg-card p-6 text-ink2">Games are being added. Check back soon.</p>}</section>
    <section><h2 className={h2}>Why choose {config.brand}</h2><div className="grid gap-4 md:grid-cols-4">{WHY.map(([t, d]) => <div key={t} className="rounded-2xl border border-line bg-card p-5"><h3 className="font-medium">{t}</h3><p className="mt-1 text-sm text-ink2">{d}</p></div>)}</div></section>
    <section id="how"><h2 className={h2}>How It Works</h2><ol className="grid gap-4 md:grid-cols-4">{STEPS.map(([t, d], i) => <li key={t} className="rounded-2xl border border-line bg-card p-5"><div className="mb-3 grid h-8 w-8 place-items-center rounded-full bg-elevated text-sm text-hi">{i + 1}</div><h3 className="font-medium">{t}</h3><p className="mt-1 text-sm text-ink2">{d}</p></li>)}</ol></section>
    {popular.length > 0 && <section><h2 className={h2}>Popular Top-Ups</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{popular.map((p) => <Link key={p.id} href={`/games/${p.game.slug}`} className="rounded-2xl border border-line bg-card p-5 transition hover:border-hi"><p className="text-xs text-mute">{p.game.name}</p><h3 className="mt-1 font-medium">{p.name}</h3><p className="mt-2 text-lg font-semibold text-hi">{ngn(p.retailPrice)}</p></Link>)}</div></section>}
    <section className="rounded-2xl border border-line bg-bg2 p-6 md:p-8"><h2 className={h2}>Built to be trusted</h2><ul className="grid gap-3 text-ink2 md:grid-cols-2"><li>🔒 Payments are processed securely by our payment provider.</li><li>📦 Every order has a reference and a live status page.</li><li>💬 Real support on WhatsApp and email if something goes wrong.</li><li>↩️ If we can't deliver a top-up, we refund you. <Link href="/refund-policy" className="text-hi">Read our Refund Policy</Link>.</li></ul></section>
    <section><h2 className={h2}>Questions</h2><div className="max-w-2xl space-y-3">{FAQ.slice(0, 5).map(([q, a]) => <details key={q} className="rounded-xl border border-line bg-card p-4"><summary className="cursor-pointer font-medium">{q}</summary><p className="mt-2 text-ink2">{a}</p></details>)}</div><Link href="/faq" className="mt-4 inline-block text-hi">See all questions →</Link></section>
    <section className="rounded-2xl border border-line bg-gradient-to-br from-elevated to-bg2 p-8 text-center"><h2 className="text-2xl font-semibold">Need help with an order?</h2><p className="mt-1 text-ink2">Message us with your Order ID and we'll sort it out.</p><div className="mt-5 flex flex-wrap justify-center gap-3"><a href={`https://wa.me/${config.whatsapp}`} className="rounded-xl bg-green-700 px-6 py-3">WhatsApp Support</a><a href={`mailto:${config.supportEmail}`} className="rounded-xl border border-line px-6 py-3">Email us</a><Link href="/track-order" className="rounded-xl border border-line px-6 py-3">Track Order</Link></div></section></div>);
}
