"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Game, Product } from "@/types";
function useSend() {
  const r = useRouter(); const [msg, setMsg] = useState("");
  const send = async (body: object) => { const j = await fetch("/api/admin/catalog", { method: "POST", body: JSON.stringify(body) }).then((x) => x.json()).catch(() => ({ ok: false, message: "Network error. Try again." })); setMsg(j.message); if (j.ok) r.refresh(); return !!j.ok; };
  return { msg, send };
}
const inp = "w-full rounded-lg border border-line bg-bg2 px-2 py-1.5", card = "mt-6 rounded-2xl border border-line bg-card p-5";
const Tg = ({ on, onClick, label }: { on?: boolean; onClick: () => void; label: string }) => <button onClick={onClick} aria-pressed={!!on} className={`rounded-lg border px-2.5 py-1 text-xs ${on ? "border-brand text-ink" : "border-line text-mute"}`}>{label}</button>;
const Msg = ({ m }: { m: string }) => (m ? <p role="status" className="mb-3 text-sm text-amber-300">{m}</p> : null);
function PRow({ p, gname, send }: { p: Product; gname: string; send: (b: object) => Promise<boolean> }) {
  const [price, setPrice] = useState(String(p.retailPrice)), [cost, setCost] = useState(String(p.supplierCost)), dirty = +price !== p.retailPrice || +cost !== p.supplierCost;
  return (<tr className="border-t border-line"><td className="p-2">{gname}</td><td className="p-2">{p.name}</td><td className="p-2"><input aria-label={`Retail price ${p.name}`} className={inp} style={{ width: 100 }} inputMode="numeric" value={price} onChange={(e) => setPrice(e.target.value)} /></td><td className="p-2"><input aria-label={`Supplier cost ${p.name}`} className={inp} style={{ width: 100 }} inputMode="numeric" value={cost} onChange={(e) => setCost(e.target.value)} /></td><td className="p-2">{+price > 0 ? Math.round(((+price - +cost) / +price) * 100) : 0}%</td>
    <td className="p-2">{dirty && <button className="rounded-lg bg-brand px-2.5 py-1 text-xs" onClick={() => send({ type: "product.update", id: p.id, retailPrice: +price, supplierCost: +cost })}>Save</button>}</td>
    <td className="p-2"><div className="flex gap-1"><Tg on={p.active} label="Active" onClick={() => send({ type: "product.update", id: p.id, active: !p.active })} /><Tg on={p.featured} label="Featured" onClick={() => send({ type: "product.update", id: p.id, featured: !p.featured })} /><Tg on={p.popular} label="Popular" onClick={() => send({ type: "product.update", id: p.id, popular: !p.popular })} /></div></td></tr>);
}
export function ProductsEditor({ games, products }: { games: Game[]; products: Product[] }) {
  const { msg, send } = useSend(); const [f, setF] = useState({ gameId: games[0]?.id ?? "", name: "", denomination: "", retailPrice: "", supplierCost: "", supplierProductId: "" }); const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setF({ ...f, [k]: e.target.value });
  return (<><Msg m={msg} /><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-left text-mute"><tr>{["Game", "Product", "Retail ₦", "Supplier cost ₦", "Margin", "", "Flags"].map((h) => <th key={h} className="p-2 font-normal">{h}</th>)}</tr></thead><tbody>{products.map((p) => <PRow key={p.id} p={p} gname={games.find((g) => g.id === p.gameId)?.name ?? ""} send={send} />)}</tbody></table></div>
  <div className={card}><h2 className="mb-3 font-medium">Add denomination</h2><div className="grid gap-3 md:grid-cols-3"><select aria-label="Game" className={inp} value={f.gameId} onChange={set("gameId")}>{games.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select><input aria-label="Name" placeholder="Name e.g. 500 Diamonds" className={inp} value={f.name} onChange={set("name")} /><input aria-label="Denomination" placeholder="Amount e.g. 500" inputMode="numeric" className={inp} value={f.denomination} onChange={set("denomination")} /><input aria-label="Retail price" placeholder="Retail price ₦" inputMode="numeric" className={inp} value={f.retailPrice} onChange={set("retailPrice")} /><input aria-label="Supplier cost" placeholder="Supplier cost ₦" inputMode="numeric" className={inp} value={f.supplierCost} onChange={set("supplierCost")} /><input aria-label="Supplier product ID" placeholder="Supplier SKU (placeholder ok)" className={inp} value={f.supplierProductId} onChange={set("supplierProductId")} /></div>
  <button className="mt-3 rounded-xl bg-brand px-5 py-2.5" onClick={async () => { if (await send({ type: "product.add", gameId: f.gameId, name: f.name, denomination: +f.denomination, retailPrice: +f.retailPrice, supplierCost: +f.supplierCost, supplierProductId: f.supplierProductId })) setF({ ...f, name: "", denomination: "", retailPrice: "", supplierCost: "", supplierProductId: "" }); }}>Add denomination</button></div></>);
}
export function GamesEditor({ games }: { games: Game[] }) {
  const { msg, send } = useSend(); const [f, setF] = useState({ name: "", slug: "", category: "Football", fieldLabel: "Player ID", description: "" }); const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setF({ ...f, [k]: e.target.value });
  return (<><Msg m={msg} /><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="text-left text-mute"><tr>{["#", "Name", "Slug", "Category", "ID field", "Sort", "Flags"].map((h) => <th key={h} className="p-2 font-normal">{h}</th>)}</tr></thead><tbody>{games.map((g) => <tr key={g.id} className="border-t border-line"><td className="p-2">{g.sortOrder}</td><td className="p-2">{g.name}</td><td className="p-2">{g.slug}</td><td className="p-2">{g.category}</td><td className="p-2">{g.playerFields[0]?.label}</td><td className="p-2"><div className="flex gap-1"><button aria-label={`Move ${g.name} up`} className="rounded border border-line px-2" onClick={() => send({ type: "game.update", id: g.id, sortOrder: g.sortOrder - 1 })}>↑</button><button aria-label={`Move ${g.name} down`} className="rounded border border-line px-2" onClick={() => send({ type: "game.update", id: g.id, sortOrder: g.sortOrder + 1 })}>↓</button></div></td><td className="p-2"><div className="flex gap-1"><Tg on={g.active} label={g.active ? "Active" : "Hidden"} onClick={() => send({ type: "game.update", id: g.id, active: !g.active })} /><Tg on={g.featured} label="Featured" onClick={() => send({ type: "game.update", id: g.id, featured: !g.featured })} /></div></td></tr>)}</tbody></table></div>
  <div className={card}><h2 className="mb-3 font-medium">Add game</h2><div className="grid gap-3 md:grid-cols-3"><input aria-label="Game name" placeholder="Game name" className={inp} value={f.name} onChange={set("name")} /><input aria-label="Slug" placeholder="Slug (optional)" className={inp} value={f.slug} onChange={set("slug")} /><select aria-label="Category" className={inp} value={f.category} onChange={set("category")}>{["Football", "Battle Royale", "FPS", "Mobile Games"].map((c) => <option key={c}>{c}</option>)}</select><input aria-label="Player ID field label" placeholder="Player ID field label" className={inp} value={f.fieldLabel} onChange={set("fieldLabel")} /><input aria-label="Description" placeholder="Short description" className={`${inp} md:col-span-2`} value={f.description} onChange={set("description")} /></div>
  <button className="mt-3 rounded-xl bg-brand px-5 py-2.5" onClick={async () => { if (await send({ type: "game.add", ...f, slug: f.slug || undefined, description: f.description || undefined })) setF({ ...f, name: "", slug: "", description: "" }); }}>Add game</button><p className="mt-2 text-xs text-mute">New games stay hidden until they have an active denomination and you enable them.</p></div></>);
}
